### ISSUE TITLE
Exponential Backoff?

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-python#107]
In regards to #106, I'm wondering if we should implement exponential backoff in our client -- this would be sort of nice, as any 5xx errors will get retried automatically after a short wait. This would improve client application stability in a 'clean' way -- and would still allow people to make async use of the library with stuff like gevent.

Any thoughts?

**Comment by denibertovic** [comment]
@rdegges theres a PR for this here: #109 

Enabling users to use async (like gevent) will require some effort though. I will compose a more detailed response with some concerns and ideas.

**Comment by denibertovic** [comment]
Hi @rdegges . I promised to outline a few things problems with async usage here. So here goes...

Currently this will not work out of the box just by using gevent monkey patching. To be clear, the time.sleep(...) we use to implement the incremental backoff will get patched and be cooperative but the actual HTTP request is still very much blocking. This is because of the way requests internals work and there are projects like grequests (https://github.com/kennethreitz/grequests)
which should work with gevent. 

However, this requires rewriting the library (stormpath-sdk-poython...or specifically the HTTP Executor parts) to use grequests instead of requests. And possibly handle some weird edge cases. 

Now the tricky part...Python has multiple async solutions like: gevent, tulip/asyncio, twisted....
It would be unwise to hardcode gevent in the picture because then if a user is using asyncio in his application it's very hard (or impossible) to start using strompath alongside. This is important especially since asyncio/tulip is blessed as the standard for any future async stuff (it only landed in 3.4.).
Users that are not using Python 3.4., however, must use other options (like gevent, twisted or trollius which is a kind of port of tulip to python 2.7.).

The way I see it, we would need to implement a separate `HttpExecutor` class for every one of these technologies and let the users specify which one to use while instantiating the `Client` (and fall back to a default). 

It would perhaps be wise to ask the users which of these (gevent, tulip etc...) they use the most
and start with that, and then gradually add the others as needed.

How does that sound?

**Comment by rdegges** [comment]
@denibertovic this is 100% what I expect (and I think other people, too).

99% of people out there use requests, and 99% of them are OK with libraries using it too, so I think that's OK with us ^^

I say we leave it as is for now, and if we eventually get requests for supporting that stuff we'll take it into consideration ^
