### ISSUE TITLE
Account.id

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-python#115]
It's come to my attention (from a few user email) that it'd be nice to have an Account.id property (really, Resource.id).

The use case is this:

A lot of people are writing their own user wrappers around our API. So for instance, they'll build something like:

api.blah.com/v1/users <-- create/update/delete users

And for this use case, these developers want to be able to delete users by id, eg:

DELETE api.blah.com/v1/users/blkj23523

Right now, our resources only have an href property, which requires the developer to manually parse out the actual ID.

Here's my suggestion:

We modify our base resource to include an ID property that parses the href attribute and handles this stuff transparently.

Thoughts?

**Comment by senko** [comment]
My 2¢:

This would shadow any `id` property that Stormpath service (ie REST API) might choose to expose in the future. At that point, we'd either have to break the API (to rename our `id` property) or cause inconsistency with different wrappers (if we map REST `id` to something else in the Python SDK).

This is why I'm wary of adding any methods or attributes to Resource. Of course, doing so is unavoidable (we risk shadowing with any attribute we add to Resource class), but in this case choosing a name less likely to cause a problem might be prudent. For example, `get_id()` method instead of `id` property.

In the case that other wrappers do (or plan to) add similar property, and/or it's blessed by the REST endpoint authors, a simple `id` would indeed be better than `get_id()`.

**Comment by rdegges** [comment]
@senko I am actually speaking with Les about this right now -- apparently we ARE going to expose this publicly very soon. So this might work just fine =)

**Comment by senko** [comment]
Awesome, then :)

**Comment by kateabbasi** [comment]
ID property will help us a lot. Right now we have to pass username in the URI to our Stormpath API wrapper. Then, we have to "search" Stormpath directory to find the user object. It will definitely be more efficient to just retrieve the user object using ID. 

@rdegges Any idea how soon is "very soon" for the new release?

**Comment by rdegges** [comment]
@omgitstom any idea what the timeframe for this looks like?

@kateabbasi thanks for chiming in! User feedback is super helpful for prioritizing things. @omgitstom is in charge of our product timeline, so he can give a better estimate than myself ^^

**Comment by rdegges** [comment]
Bump @omgitstom

**Comment by rdegges** [comment]
Bump @omgitstom

**Comment by rdegges** [comment]
Bump @omgitstom

**Comment by rdegges** [comment]
Bump @omgitstom

**Comment by rdegges** [comment]
I'm closing this as it's going to be included in the core API eventually, and this it no longer a python sdk issue.

**Comment by andremilk** [comment]
Any news on this?

**Comment by rdegges** [comment]
The product hasn't been updated to include this in the core API service yet. Ping @omgitstom

**Comment by andremilk** [comment]
Well, one workaround for this is 
`account_id = account.href.split('/accounts/')[1]`
