### ISSUE TITLE
Custom Data Inconsistency Fix / Idea

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-python#119]
Heyo.

So, I've got an idea that might help with our random test failures. I was doing some debugging, and it appears that most of our failures happen due to custom data inconsistency. So for instance, we'll have some custom data, change the value, save it, then assert that the old stuff = the new stuff.

This tends to happen most frequently with deletes:

- Have custom data like `{'hi': 'there', 'yo': 'dude'}`
- Delete a key: `{'hi': 'there'}` (*'yo' was deleted*)
- Call `custom_data.save()`
- `assert 'yo' not in custom_data` # fails

Upon closer inspection, it looks as if this may be because we're forcing an ensure_data in all of our underlying calls inside of `CustomData` (eg: https://github.com/stormpath/stormpath-sdk-python/blob/develop/stormpath/resources/custom_data.py#L67).

I believe this issue could be fixed (*and we could probably speed up client execution as well*) if we smartly handle 'refreshing' the resources client-side in the SDK.

EG: If we have just deleted keys, don't bother calling `_ensure_data` to pull the latest changes -- just roll with what's in-memory.

This same stuff also applies to a lot of the other internal methods.

I'm not sure if this is a good idea or not -- namely because it's masking the eventual consistency of our custom data store, but it would certainly solve odd problems that customers will more than likely run into in the wild.

Thoughts?

**Comment by denibertovic** [comment]
Hi @rdegges

>EG: If we have just deleted keys, don't bother calling _ensure_data to pull the latest changes -- just roll with what's in-memory.

>This same stuff also applies to a lot of the other internal methods.

I don't think this is a good idea. Calling `_ensure_data` was deliberately added because we always want to ask the Cache for data first (as we assume the cache is fast and correct), and we want to avoid asking the Object local memory for data (ie. we refresh from Cache every change we get). This was decided because of various issue previously. 

More info and back story can be found in an earlier PR here: https://github.com/stormpath/stormpath-sdk-python/pull/44

Since there's a pending PR to make customData use the Cache store I don't think this will be an issue any more.

**Comment by rdegges** [comment]
Agreed. Closing this.
