### ISSUE TITLE
Expose Timestamp Fields in custom_data

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-python#131]
Right now our custom_data resource doesn't show the built-in timestamp stuff documented here: http://docs.stormpath.com/rest/product-guide/#retrieve-custom-data

If you have an account object, and say:

```python
print dict(account.custom_data)
```

You'll only see the user-specified fields, not the built-in ones:

- `created_at`
- `modified_at`

We should expose these to the user so that a user can say:

```python
account.custom_data['created_at']
account.custom_data['modified_at']
```

**NOTE**: I believe this also applies to provider data for social stuff, but I'm not 100% sure, we should check anyway though =)

**Comment by avojnovicDk** [comment]
Right now, there are already `created_at` and `modified_at` attributes on custom data (`account.custom_data.created_at` for example), but not in the custom data dict (`account.custom_data['created_at']`).
I modified the CustomData resource so it exposes these fields as dict items, too. Also, I parse them to datetime (as @omgitstom suggested during last week's meeting) before adding them to dictionary.
Now I see that `account.custom_data.created_at` is string, and the dict value `account.custom_data['created_at']` is datetime. I'm really not sure if this is a problem and what to do with it. I can't parse `account.custom_data.created_at` to datetime without breaking backwards compatibility and it may be confusing for users this way because they will sometimes get string, and sometimes datetime when trying to access the same field.
Any thoughts on this are welcome.

**Comment by rdegges** [comment]
I think we should 100% expose them all as datetime objects in python. If you add that in, I'll just cut a new major release.

I'm not really much for support backwards compatibility for this stuff, as it's wayyyy easier / more convenient for developers to have the time object itself ^^ I don't mind cutting a new major release at all =)

**Comment by avojnovicDk** [comment]
Great! I agree that datetime objects are more convenient for this. I'll make existing one datetime, too.
Oh, and I checked the provider data and it has `created_at` and `modified_at` exposed in the same way the custom data has (only string attributes).

**Comment by rdegges** [comment]
Awesome! Thank you very much =)
