### ISSUE TITLE
Proposal: ORM-Style Queries

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-python#138]
Hi all, this is a proposal for making a major change to the way our library works. Here's my proposal:

Currently, when iterating over Stormpath collection resources (`Accounts`, `Applications`, `Directories`, etc...), we do so by creating a generator behind the scenes and making the collection resource itself a property.

For example, to iterate over a list of Applications, you would write:

```python
>>> for application in client.applications:
>>>     print application.name
```

This works fine, although it can be a bit confusing. As a developer who's viewing this, a few questions immediately come to mind:

- Is this making an API call or is this somehow auto-populated when my client was created?
- How many objects are in this array / whatever?
- Is this a generator?
- Can I use slices on it?
- etc...

I think a much more appropriate way to write this, would be modeled after something like [Django's ORM](https://docs.djangoproject.com/en/1.7/topics/db/queries/) or the [SQLAlchemy ORM](http://docs.sqlalchemy.org/en/rel_0_9/orm/query.html). Both of these ORMs are widely familiar to Python programmers, and both contain a very standardized set of options that makes logical and intuitive sense for developers working with collections of items.

Here's how the above example might look with my proposal implemented:

```python
>>> for application in Application.objects.all():
>>>     print application.name
```

If we wanted to return only a subset of applications (first 5), we could write:

```python
>>> for application in Application.objects.all()[:5]
>>>     print application.name
```

Which would automatically execute a limit query behind the scenes for us.

Furthermore, we could add in `filter` logic like Django does, to ensure a consistent query API, eg:

```python
>>> from stormpath.orm import startswith
>>> for application in Application.objects.filter(name__startswith='staging-'):
>>>     print application.name
```

I think this would provide a more 'pythonic' feel to our library, and greatly improve the UX. It'd also make it possible to do more things intuitively without referering to the documentation, as many developers are already familiar with the syntax suggested.

In terms of modeling, I think we should model things after the Django ORM as the principal reference, as their ORM is quite a bit simpler than SQLalchemy, and also exposes a wide variety of useful (but not terribly specific) tooling.

**Comment by avojnovicDk** [comment]
Hi Randall,

I don't think that we should model Stormpath Python SDK after the Django ORM. This is mostly due to the different purpose of these two libraries (as we are obviously not building ORM), but also because of the variety among different Python frameworks.

I'm afraid that this change would result in a more "Djangonic" feel, as not all Python programers use Django, and Django's ORM and SQLAlchemy ORM have very different syntax. This would probably confuse the non-Django users even more. And as Django user myself, I think that this would confuse the Django users as well because they would expect for some things that work in Django to work in the SDK. For example, in Django you can delete objects in bulk. I would expect that something like this will work:
```
Application.objects.all().delete()
```
But it wouldn't because we don't have that feature.


That being said, I will comment the proposed features.

### using Application.objects.all() instead of client.applications


First, with `Application.objects.all()` we are not specifying the client we are using. In Django, database connection is opened when it first makes a query (using database settings in settings.py) and then it is reused. We could probably do something similar with the client, while allowing user to specify client settings in some other way, as right now they are explicitlly specifying them when creating a client:
```
client = Client(cache_options=cache_opts, api_key=api_key)
```
I think that this is doable but the only thing that we would acomplish with this is that getting applications would have Django syntax.

Also, `objects` in `Application.objects.all()` is default Django manager (https://docs.djangoproject.com/en/1.7/topics/db/managers/) and doesn't have a purpose (or at least I don't see it) for Stormpath Python SDK. Also, as Django developer, I would expect I can write my own custom manager and use it on Application and would be confused if I couldn't.
For the `all()` part, it is used in Django to call `get_queryset()` function on that manager which can be overriden to change the returned queryset (for example, filter it). Stormpath Python SDK always gets all objects in collection as it takes href of the collection (eg. "https://api.stormpath.com/v1/tenants/$YOUR_TENANT_ID/applications") and currently it doesn't support overriding this behavior.

### slicing (Application.objects.all()[:5])

This already works with `applications[:5]` - it executes a limit query. Am I missing something?

### filter logic like Django does

Right now, filtering is done by calling search() function and passing it a dict, eg.:
```
applications.search({'name': 'My application'})
```
And this is not very pretty, I agree. But there is also query function (I think that it is for some reason undocumented) that looks good:
```
applications.query(name='My application')
```
For your `startswith` example this would look like this:
```
applications.query(name='staging-*')
```
And IMHO, this is very readable. To switch to Django filtering, we would have to implement some kind of conversion between Django and Stormpath REST filter logic and cover all the edge cases (for example, if someone passes `name__startswith='*'`), and all we would achieve would be filtering that looks like Django filtering (and again, would not be Django filtering and Django users couldn't use it the way they use Django filtering). 

So maybe it would be more useful if we update Python SDK docs (for example, with info for this query function), so users have better info on how to use the current SDK than to change it with something that could confuse them even more?

**Comment by rdegges** [comment]
After thinking about this, I believe you're right.

In the context of what we're trying to do here, it doesn't really make much sense to introduce the overhead of the Django-esque ORM stuff. Especially since implementing all of the helpers (eg: object managers would have no place in our code) wouldn't make sense.

Thanks so much for reviewing this!
