### ISSUE TITLE
Proposal: API Authentication Improvements

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-python#146]
This is a proposal that I think would help improve the quality of our API authentication stuff. Here's what I'd like to see.

**Application.authenticate_api_request()**:

- This should be the 'one size fits all' API authentication method. It should be able to authenticate any type of API request: Basic Auth AND OAuth2 (any of the four grant types).
- It should use whatever information is passed into this method to determine the BEST type of authentication to use (grant types in the body, in the URL params, etc).

**Application.authenticate_basic_api_request(headers)**:

- This should *only* authenticate HTTP Basic Auth requests.
- It should take in (required) the HTTP Authorization header value as a dict. EG: { 'authorization': 'Basic <blah>' }

**Application.authenticate_oauth2_api_request(headers, uri=None, body=None)**:

- This should authenticate *only* OAuth2 API requests. It should look for the proper header, URI (to confirm grant types / etc), and body (if available).

**Application.authenticate_oauth2_password_request(headers, uri=None, body=None)**:

- This should *only* support authenticating OAuth2 Password Grant type requests.

**Application.authenticate_oauth2_authorization_code_request(headers, uri=None, body=None)**:

- This should *only* support authenticating OAuth2 Authorization Code grant type requests.

**Application.authenticate_oauth2_implicit_request(headers, uri=None, body=None)**:

- This should *only* support authenticating OAuth2 Implicit grant type requests.

**Application.authenticate_oauth2_client_credentials_request(headers, uri=None, body=None)**:

- This should *only* support authenticating OAuth2 client credentials grant type requests.

What do ya'll think?

**Comment by lhazlewood** [comment]
@robertjd and I had a discussion about this a bit ago: the Java SDK is going to be refactored before 1.0 final to extract all of these methods and put them into separate use-case/protocol-specific builders/helpers.

The current design (and the proposed suggestion) violates the Interface Segregation Principle and is very tightly coupled to oauth concerns and permutations.  For example, what happens when SAML SSO is comes in to play? Then the next best protocol after that?  You'll have dozens of `authenticate*` methods.  Nasty, nasty, nasty.  And hard to maintain, and causes all sorts of forced dependencies on the core Application resource implementation.

Instead, the SDK user should choose an authenticator based on the thing that they want to do, e.g.

```javascript
new OAuth2Authenticator(application). /*configure various things here */ .authenticate();
```

This is loosely coupled, but highly cohesive and does not pollute the main Application resource method space.  It is flexible and only forces change on the relevant builder/authenticator - no other code is forced to be changed when other protocols are supported or refactored, etc.

All of our SDKs should follow suit, as these design principles (Interface Segregation Principle, Single Responsibility Principle, etc) are generic and not language specific nor even programming paradigm specific.
