### ISSUE TITLE
Support Password Grant

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-python#202]
I just merged in the new API authentication classes, but realized we still need to get the password authenticator included. It should work like client credentials, but should take in a username (or email) and password, and return an access token.

**Comment by nkwood** [comment]
I was taking a look at implementing this feature because it fits with a project I'm working on (we would like to issue access tokens upon username/password without the need to have an API key created on Stormpath for the account), but hit something that confuses me. I assumed this would just have an OAuthResourceOwnerPasswordCredentialsRequestAuthenticator which would take username/password and output the token. I read [rfc6749 section 4.3](http://tools.ietf.org/html/rfc6749#section-4.3) and the [oathlib docs on Resource Owner Password Credentials Grant](http://oauthlib.readthedocs.org/en/latest/oauth2/grants/password.html).

My understanding is the request should be application/x-www-form-urlencoded and the body should contain grant_type=password, the username/password key/value fields, and optionally the scope. However, when I look at the example in 4.3.2 of rfc6749 it shows this, but also shows a Authorization header. Shouldn't a resource owner password credentials request (just username/password) not require any other client authentication?

Also, is the plan to issue both an access_token and a refresh_token if requested?

**Comment by nkwood** [comment]
I found [this documentation for the REST API](http://docs.stormpath.com/guides/token-management/#using-stormpath-to-generate-an-oauth-20-access-tokens) which answered my question. I *think* I understand the flow now. :smile:

**Comment by omgitstom** [comment]
https://github.com/stormpath/stormpath-sdk-java/issues/232

**Comment by theoegui** [comment]
Hey dude,
How are you doing?
I'm trying to understand what exactly does Stormpath/python do?

Sincerely,

Theo Eguia

**Comment by theoegui** [comment]
im using this site too
http://docs.stormpath.com/guides/token-management/

**Comment by nkwood** [comment]
I'm trying to use the password grant authenticator that has been merged into the develop branch. However, I might be misunderstanding the behavior expected from PasswordGrantAuthenticator. The assumption I'm operating under is this should offer the same or similar functionality as using the REST API `/oauth/token` endpoint. Doing this works just fine for me:
```python
# Uses the REST API - works fine.
def getTokenWithPassword(username, password):
    APP_ID = '4rNlYtZAvN5uAsjTTDsfYa'
    uri = 'https://api.stormpath.com/v1/applications/' + APP_ID + '/oauth/token'
    payload = {'grant_type': 'password',
               'username': username,
               'password': password}
    result = requests.post(uri, data=payload, auth=(API_KEY_ID, API_KEY_SECRET))
    if result.status_code == 200:
        return result.json()
    else:
        return None
```
I try to do the same with the python SDK like so:
```python
# Uses the Python SDK
# PasswordGrantAuthenticator fails w/ 401 "Authentication with a valid API Key is required."
def new_getTokenWithPassword(username, password):
    client = Client(api_key_file=API_KEY_PATH)
    application = client.applications.get(MY_APP_URL)
    # For testing verify the username/password are correct - works fine:
    try:
        auth_attempt = application.authenticate_account(username, password)
    except StormpathError:
        return 'Auth failed.'

    # Can use get_access_token(), but this only gives a single locally generated access token
    # i.e. no refresh token and not available in StormPath account resource:
    token = auth_attempt.get_access_token()
    jwt_authenticator = JwtAuthenticator(application)
    if jwt_authenticator.authenticate(token):
        print("Token valid with Stormpath")
    else:
        print("Token invalid with Stormpath") # Stormpath doesn't know the token.
    if jwt_authenticator.authenticate(token, local_validation=True):
        print("Token valid locally") # Validates fine locally.
    else:
        print("Token invalid locally")

    # Using PasswordGrantAuthenticator fails w/ 401 "Authentication with a valid API Key is required."
    # as if the API call made by PasswordGrantAuthenticator isn't including the StormPath API Keys:
    pg_authenticator = PasswordGrantAuthenticator(application)
    pg_auth_result = pg_authenticator.authenticate(username, password)
    if pg_auth_result is not None:
        return 'Success!'
    else:
        return 'Fail!' # This fails.
```

Am I doing this the wrong way?

**Comment by rdegges** [comment]
@avojnovicDk can you look into this?

**Comment by theoegui** [comment]
Based on the assessment/  findings, I should be more in tuned with python.
Give me one moment

**Comment by avojnovicDk** [comment]
@nkwood big thanks for reporting this! My live tests didn't catch this for some reason, but I reproduced it in console and fixed it.

**Comment by rdegges** [comment]
Released.

**Comment by nkwood** [comment]
This is working great for me now. Thanks @avojnovicDk and @rdegges .

**Comment by rdegges** [comment]
All thanks goes to @avojnovicDk =) Glad things are working for ya!
